import { createRequestHandler, RouterContextProvider, type ServerBuild } from 'react-router';

// Both imports below reach outside `app/`, so they can't use the `~/`
// alias. `load-context.ts` is a sibling module; `build/server` is
// generated by `react-router build` and gitignored, so tsc + eslint
// don't see it until after a build.
// eslint-disable-next-line no-restricted-imports -- `~/` alias only reaches `app/`
import type { AppLoadContext } from '../app/utils/load-context';
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - build/server/index.js is generated by `react-router build`
// eslint-disable-next-line no-restricted-imports, import/no-unresolved -- generated at build time
import * as build from '../build/server';

// Cloudflare Workers entrypoint. `wrangler.jsonc` pins `main` to this
// file with `run_worker_first: true`, so every request hits here first.
// Static-asset paths get handed back to `env.ASSETS.fetch()`; everything
// else routes through the React Router request handler.
const STATIC_PREFIXES = ['/assets/', '/fonts/', '/.well-known/'];
const STATIC_EXACT = new Set(['/favicon.ico', '/robots.txt', '/sitemap.xml']);

const requestHandler = createRequestHandler(build as unknown as ServerBuild);

// Build the RouterContextProvider that RR8 requires as `loadContext`,
// with our Cloudflare bindings + CSP nonce attached as plain properties.
// Property-based passing (not `.set(context, value)`) sidesteps a
// bundling gotcha: RR builds routes into a separate SSR bundle whose
// `createContext()` calls create context instances distinct from
// anything the worker constructs. `.set` on the worker's context
// object doesn't match `.get` on the route's — the Map is keyed by
// object identity. Property access by name works either way.
function buildLoadContext(cloudflare: { env: Env; ctx: ExecutionContext }, cspNonce: string) {
  const context = new RouterContextProvider() as unknown as AppLoadContext & RouterContextProvider;
  (context as { cloudflare?: typeof cloudflare }).cloudflare = cloudflare;
  (context as { cspNonce?: string }).cspNonce = cspNonce;
  return context;
}

// ─── CSP nonce ────────────────────────────────────────────────────────
// RR v8's SSR emits inline <script> tags for the hydration payload
// (`window.__reactRouterContext = ...`, the stream controller enqueue
// calls, and scroll-restoration). Their contents are per-request, so
// SHA-256 hashes can't cover them. Instead we mint a fresh nonce per
// request, set it on every inline script (via `<Scripts nonce>` and
// our own `<script nonce={...}>` in root.tsx), and echo the same value
// into the CSP header's `script-src 'nonce-<val>'`.
//
// 128 bits of entropy in url-safe base64 (16 random bytes → 22 chars).
function mintNonce(): string {
  const bytes = new Uint8Array(16);
  crypto.getRandomValues(bytes);
  return btoa(String.fromCharCode(...bytes))
    .replaceAll('+', '-')
    .replaceAll('/', '_')
    .replaceAll('=', '');
}

// ─── Security headers ─────────────────────────────────────────────────
// Applied to every response the Worker generates (SSR HTML, .data,
// contact action, and static assets forwarded via env.ASSETS). CSP is
// built per-request because it embeds the nonce; the other headers are
// static.
//
// style-src carries 'unsafe-inline' because 40+ components use inline
// `style={{ }}` attrs (skeleton widths, heatmap grid vars, etc.).
// Hashing every inline style declaration is impractical; the trade-off
// is documented. Everything else uses strict allow-lists.
function buildCsp(nonce: string): string {
  return [
    "default-src 'none'",
    `script-src 'self' 'nonce-${nonce}'`,
    "style-src 'self' 'unsafe-inline'",
    "img-src 'self' data:",
    "font-src 'self'",
    "connect-src 'self'",
    "manifest-src 'self'",
    "base-uri 'self'",
    "frame-ancestors 'none'",
    "form-action 'self'",
    "object-src 'none'",
  ].join('; ');
}

const STATIC_SECURITY_HEADERS: Record<string, string> = {
  'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload',
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'DENY',
  'Referrer-Policy': 'strict-origin-when-cross-origin',
  'Permissions-Policy':
    'camera=(), microphone=(), geolocation=(), interest-cohort=(), payment=(), usb=(), magnetometer=(), gyroscope=(), accelerometer=()',
};

function withSecurityHeaders(response: Response, nonce: string): Response {
  const headers = new Headers(response.headers);
  for (const [k, v] of Object.entries(STATIC_SECURITY_HEADERS)) headers.set(k, v);
  headers.set('Content-Security-Policy', buildCsp(nonce));
  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers,
  });
}

// ─── `.data` rate limit ───────────────────────────────────────────────
// RR v8's Single-Fetch `.data` endpoints return the destination
// loader's JSON payload. Real visitors hit at most a handful per
// session; bulk scrapers looping every route land here first. Cap
// 60/hour per IP: invisible to humans, breaks a curl-in-a-for-loop
// after ~7 URLs.
//
// KV key hashes the IP so the namespace isn't a readable audit trail
// of who's visiting. Sentinel `local-dev` fallback keeps the rule
// inert under `wrangler dev` where `CF-Connecting-IP` is unset.
const DATA_RATE_LIMIT_PER_HOUR = 60;

async function hashIp(ip: string): Promise<string> {
  const buf = new TextEncoder().encode(ip);
  const digest = await crypto.subtle.digest('SHA-256', buf);
  return Array.from(new Uint8Array(digest))
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('');
}

async function isDataRequestOverLimit(
  request: Request,
  env: Env,
  ctx: ExecutionContext
): Promise<boolean> {
  const ip = request.headers.get('CF-Connecting-IP') ?? 'local-dev';
  const key = `ratelimit:data:${await hashIp(ip)}`;
  const current = await env.RATELIMIT_KV.get(key);
  const count = current ? Number.parseInt(current, 10) || 0 : 0;
  if (count >= DATA_RATE_LIMIT_PER_HOUR) return true;
  // waitUntil lets the response race the KV write — the counter
  // converges within seconds and a scraper can't outrun eventually-
  // consistent reads long enough to matter (worst case: 1-2 extra
  // requests through per warm-worker window).
  ctx.waitUntil(env.RATELIMIT_KV.put(key, String(count + 1), { expirationTtl: 3600 }));
  return false;
}

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    const nonce = mintNonce();

    if (STATIC_EXACT.has(url.pathname) || STATIC_PREFIXES.some((p) => url.pathname.startsWith(p))) {
      return withSecurityHeaders(await env.ASSETS.fetch(request), nonce);
    }
    if (url.pathname.endsWith('.data')) {
      if (await isDataRequestOverLimit(request, env, ctx)) {
        return withSecurityHeaders(
          new Response('Too Many Requests', {
            status: 429,
            headers: { 'Retry-After': '3600', 'X-Robots-Tag': 'noindex' },
          }),
          nonce
        );
      }
      const context = buildLoadContext({ env, ctx }, nonce);
      const response = await requestHandler(request, context);
      const headers = new Headers(response.headers);
      // Search engines shouldn't index the raw JSON payloads.
      headers.set('X-Robots-Tag', 'noindex');
      return withSecurityHeaders(
        new Response(response.body, { status: response.status, headers }),
        nonce
      );
    }
    const context = buildLoadContext({ env, ctx }, nonce);
    return withSecurityHeaders(await requestHandler(request, context), nonce);
  },
} satisfies ExportedHandler<Env>;
