import { createRequestHandler, type ServerBuild } from 'react-router';

// eslint-disable-next-line no-restricted-imports -- `~/` alias only reaches `app/`
import { hashIp } from '../app/utils/hash-ip';
// Both imports below reach outside `app/`, so they can't use the `~/`
// alias. `load-context.ts` is a sibling module; `build/server` is
// generated by `react-router build` and gitignored, so tsc + eslint
// don't see it until after a build.
// eslint-disable-next-line no-restricted-imports -- `~/` alias only reaches `app/`
import { createAppLoadContext } from '../app/utils/load-context';
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - build/server/index.js is generated by `react-router build`
// eslint-disable-next-line no-restricted-imports -- generated at build time
import * as build from '../build/server';

// Cloudflare Workers entrypoint. `wrangler.jsonc` pins `main` to this
// file with `run_worker_first: true`, so every request hits here first.
// Static-asset paths get handed back to `env.ASSETS.fetch()`; everything
// else routes through the React Router request handler.
const STATIC_PREFIXES = ['/assets/', '/fonts/', '/.well-known/'];
const STATIC_EXACT = new Set(['/favicon.ico', '/robots.txt', '/sitemap.xml']);

const requestHandler = createRequestHandler(build as unknown as ServerBuild);

// ─── CSP nonce ────────────────────────────────────────────────────────
// RR v8's SSR emits inline <script> tags for the hydration payload
// (`window.__reactRouterContext = ...`, the stream controller enqueue
// calls, and scroll-restoration). Their contents are per-request, so
// SHA-256 hashes can't cover them. Instead we mint a fresh nonce per
// request, set it on every inline script (via `<Scripts nonce>` and
// our own `<script nonce={...}>` in root.tsx), and echo the same value
// into the CSP header's `script-src 'nonce-<val>'`.
//
// 128 bits of entropy in url-safe base64 (16 random bytes → 22 chars).
function mintNonce(): string {
  const bytes = new Uint8Array(16);
  crypto.getRandomValues(bytes);
  return btoa(String.fromCharCode(...bytes))
    .replaceAll('+', '-')
    .replaceAll('/', '_')
    .replaceAll('=', '');
}

// ─── Security headers ─────────────────────────────────────────────────
// Applied to every response the Worker generates (SSR HTML, .data,
// contact action, and static assets forwarded via env.ASSETS). CSP is
// built per-request because it embeds the nonce; the other headers are
// static.
//
// style-src carries 'unsafe-inline' because 40+ components use inline
// `style={{ }}` attrs (skeleton widths, heatmap grid vars, etc.).
// Hashing every inline style declaration is impractical; the trade-off
// is documented. Everything else uses strict allow-lists.
//
// The CSP body is 99% static, so we hoist the pre-nonce prefix and
// post-nonce suffix to module scope. Only the nonce changes per
// request, so building the header per request is just two string
// concats instead of a 10-element array + join.
const CSP_TAIL =
  "'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self';" +
  " connect-src 'self'; manifest-src 'self'; base-uri 'self';" +
  " frame-ancestors 'none'; form-action 'self'; object-src 'none'";
const CSP_HEAD_WITH_NONCE = "default-src 'none'; script-src 'self' 'nonce-";

// Static assets carry no inline scripts. Pre-computed nonce-less CSP
// keeps that path off the concat.
const CSP_STATIC_ASSETS = `default-src 'none'; script-src 'self${CSP_TAIL}`;

const STATIC_SECURITY_HEADERS: Record<string, string> = {
  'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload',
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'DENY',
  'Referrer-Policy': 'strict-origin-when-cross-origin',
  'Permissions-Policy':
    'camera=(), microphone=(), geolocation=(), interest-cohort=(), payment=(), usb=(), magnetometer=(), gyroscope=(), accelerometer=()',
};

function withSecurityHeaders(
  response: Response,
  nonce: string,
  extra?: Record<string, string>
): Response {
  const headers = new Headers(response.headers);
  for (const [k, v] of Object.entries(STATIC_SECURITY_HEADERS)) headers.set(k, v);
  headers.set(
    'Content-Security-Policy',
    nonce ? `${CSP_HEAD_WITH_NONCE}${nonce}${CSP_TAIL}` : CSP_STATIC_ASSETS
  );
  if (extra) for (const [k, v] of Object.entries(extra)) headers.set(k, v);
  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers,
  });
}

// ─── `.data` rate limit ───────────────────────────────────────────────
// RR v8's Single-Fetch `.data` endpoints return the destination
// loader's JSON payload. Real visitors hit at most a handful per
// session; bulk scrapers looping every route land here first. Cap
// 60/hour per IP: invisible to humans, breaks a curl-in-a-for-loop
// after ~7 URLs.
//
// KV key hashes the IP so the namespace isn't a readable audit trail
// of who's visiting. Sentinel `local-dev` fallback keeps the rule
// inert under `wrangler dev` where `CF-Connecting-IP` is unset.
const DATA_RATE_LIMIT_PER_HOUR = 60;

// Real client-side nav from the app sends all THREE `Sec-Fetch-*`
// headers plus a same-origin Referer. Individually each signal is
// spoofable, but a scraper has to match all four correctly to bypass
// the cap — versus checking just `Sec-Fetch-Site: same-origin` which
// is a one-header spoof if they read the source. Multiplying the
// number of matching signals raises effort meaningfully without
// affecting real visitors.
function isTrustedInternalNav(request: Request, origin: string): boolean {
  const site = request.headers.get('Sec-Fetch-Site');
  const dest = request.headers.get('Sec-Fetch-Dest');
  const mode = request.headers.get('Sec-Fetch-Mode');
  if (site !== 'same-origin' || dest !== 'empty' || mode !== 'cors') return false;
  const referer = request.headers.get('Referer');
  if (!referer) return false;
  try {
    return new URL(referer).origin === origin;
  } catch {
    return false;
  }
}

async function isDataRequestOverLimit(
  request: Request,
  env: Env,
  ctx: ExecutionContext
): Promise<boolean> {
  const ip = request.headers.get('CF-Connecting-IP') ?? 'local-dev';
  const key = `ratelimit:data:${await hashIp(ip)}`;
  const current = await env.RATELIMIT_KV.get(key);
  const count = current ? Number.parseInt(current, 10) || 0 : 0;
  if (count >= DATA_RATE_LIMIT_PER_HOUR) return true;
  // waitUntil lets the response race the KV write — the counter
  // converges within seconds and a scraper can't outrun eventually-
  // consistent reads long enough to matter (worst case: 1-2 extra
  // requests through per warm-worker window).
  ctx.waitUntil(env.RATELIMIT_KV.put(key, String(count + 1), { expirationTtl: 3600 }));
  return false;
}

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);

    // Static assets carry no inline scripts, so they get the nonce-less
    // CSP and skip the mint entirely.
    if (STATIC_EXACT.has(url.pathname) || STATIC_PREFIXES.some((p) => url.pathname.startsWith(p))) {
      return withSecurityHeaders(await env.ASSETS.fetch(request), '');
    }

    const nonce = mintNonce();

    if (url.pathname.endsWith('.data')) {
      if (
        !isTrustedInternalNav(request, url.origin) &&
        (await isDataRequestOverLimit(request, env, ctx))
      ) {
        return withSecurityHeaders(new Response('Too Many Requests', { status: 429 }), nonce, {
          'Retry-After': '3600',
          'X-Robots-Tag': 'noindex',
        });
      }
      const context = createAppLoadContext({ env, ctx }, nonce);
      const response = await requestHandler(request, context);
      // Merge `X-Robots-Tag: noindex` in the same header pass as the
      // rest of the security headers — avoids a second Response wrap.
      return withSecurityHeaders(response, nonce, { 'X-Robots-Tag': 'noindex' });
    }
    const context = createAppLoadContext({ env, ctx }, nonce);
    return withSecurityHeaders(await requestHandler(request, context), nonce);
  },
} satisfies ExportedHandler<Env>;
