import { createRequestHandler, RouterContextProvider, type ServerBuild } from 'react-router';

// Both imports below reach outside `app/`, so they can't use the `~/`
// alias. `load-context.ts` is a sibling module; `build/server` is
// generated by `react-router build` and gitignored, so tsc + eslint
// don't see it until after a build.
// eslint-disable-next-line no-restricted-imports -- `~/` alias only reaches `app/`
import { cloudflareContext } from '../app/utils/load-context';
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - build/server/index.js is generated by `react-router build`
// eslint-disable-next-line no-restricted-imports, import/no-unresolved -- generated at build time
import * as build from '../build/server';

// Cloudflare Workers entrypoint. `wrangler.jsonc` pins `main` to this
// file with `run_worker_first: true`, so every request hits here first.
// Static-asset paths get handed back to `env.ASSETS.fetch()`; everything
// else routes through the React Router request handler.
const STATIC_PREFIXES = ['/assets/', '/fonts/', '/.well-known/'];
const STATIC_EXACT = new Set(['/favicon.ico', '/robots.txt', '/sitemap.xml']);

const requestHandler = createRequestHandler(build as unknown as ServerBuild);

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    if (STATIC_EXACT.has(url.pathname) || STATIC_PREFIXES.some((p) => url.pathname.startsWith(p))) {
      return env.ASSETS.fetch(request);
    }
    const context = new RouterContextProvider();
    context.set(cloudflareContext, { env, ctx });
    return requestHandler(request, context);
  },
} satisfies ExportedHandler<Env>;
